AWSTemplateFormatVersion: 2010-09-09
Description: |
  Self-Study Roman-Numerals converter project with a Security Group and an Instance
Parameters:
  KeyName:
    Description: Enter Your Key Pair Name
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  MySecGroupWebSever:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP-SSH Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bef6cc322bfff646
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecGroupWebSever
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}

      UserData: !Base64 |
        #! /bin/bash
        yum update -y
        yum install python3
        pip install flask
        cd /home/ec2-user
        FOLDER="https://raw.githubusercontent.com/osman-e/my-projects/main/Project-001-Roman-Numerals-Converter"
        wget ${FOLDER}/app.py
        mkdir templates && cd templates
        wget ${FOLDER}/templates/index.html
        wget ${FOLDER}/templates/result.html
        cd ..
        python3 app.py

Outputs:
  WebsiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MyInstance.PublicDnsName
